name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      COVERAGE_THRESHOLD: 100

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24.2"

      - name: Install Dependencies
        run: go mod tidy

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.2

      - name: Run Tests
        run: make coverage

      - name: Check Coverage Threshold
        run: |
          COVERAGE=$(go tool cover -func=coverage.out | grep total | awk '{print $3}' | sed 's/%//')
          if [ "$(echo "$COVERAGE < $COVERAGE_THRESHOLD" | bc -l)" -eq 1 ]; then
            echo "Code coverage is below $COVERAGE_THRESHOLD%. Coverage is ${COVERAGE}%"
            exit 1
          fi
          echo "Code coverage is ${COVERAGE}% — All good!"
